### ISSUE TITLE
Error on resgistration

### ISSUE THREAD

**Issue by tortosi** [paintballrefjosh/MaNGOSWebV4#23]
Perdon, for my english.

If i have activated the confirmation via email i recive theese error:

`Array ( )
1`

i send a image:
![captura de 2017-03-10 19-38-05](https://cloud.githubusercontent.com/assets/160920/23808581/a837a940-05ca-11e7-9ce4-2e44371f67ac.png)

**Comment by paintballrefjosh** [comment]
Thanks for posting an issues.  I'm unable to reproduce at this time as it works correctly for me.  I would need the error posted in English to be able to further assist.  Thanks!

![image](https://cloud.githubusercontent.com/assets/16195063/23810480/7a29903c-0597-11e7-96d7-ac4fb864cb55.png)
