### ISSUE TITLE
No registration mail received

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#27]
When i try to register a new account and fill all needed data the system validates me and shows me a message telling me that i need to check my inbox to validate my account. Problem is that i didnt receive any mail. 

My server email settings are fine because if i use the Send mail link from the Admin panel then i receive the mail without problems..

**Comment by paintballrefjosh** [comment]
I saw a similar issue.  Double check your spam folder, that's where mine ended up.

**Comment by Cubansephiroth** [comment]
I triple checked my spam folder no mail at all and i still can receive emails fine from admin panel.
Here is my email settings...

Email relay type: MTA
MTA - SMTP Host: Localhost
MTA - SMTP Port: 25
MTA - Use Secure: No

if i change MTA to SMTP then i cant even send mail through admin Panel
here is a pic of the error
![error](https://cloud.githubusercontent.com/assets/11562843/24306599/7f731a9e-1097-11e7-836f-ccbcd5a8af72.jpg)

**Comment by paintballrefjosh** [comment]
Ok I see now.  I'm not sure exactly what the MTA connector does and never have tested it.  I currently use SMTP but you need to make sure the host, port, secure, type, user & pass are set correctly.  You can use a simple gmail account to test with.

![image](https://cloud.githubusercontent.com/assets/16195063/24320089/f5f5a9ca-10fb-11e7-82f6-3dc6f4fef9fb.png)

**Comment by Cubansephiroth** [comment]
Thanks for your help, ill try to set up an smtp account and comment later..

**Comment by Cubansephiroth** [comment]
same configuration as your picture with a test gmail account and same error from my previous attachment. I will clone the project again with no editing at all and i will test again.

**Comment by paintballrefjosh** [comment]
Gmail settings are as follows

Hostname: **smtp.gmail.com**
Use secure: **Yes**
Port: **465** Auth: **SSL**
Port: **587** Auth: **TLS**

Then your email as the username and appropriate password.

Source: https://support.google.com/a/answer/176600?hl=en

**Comment by Cubansephiroth** [comment]
tested with both SSL and TLS and try to send mail from Admin Panel and still got the same errors

![error](https://cloud.githubusercontent.com/assets/11562843/24376107/b233d4d2-1308-11e7-8ab4-10062b7666d9.jpg)

**Comment by paintballrefjosh** [comment]
I may have found a related issue.  It doesn't appear that the email function uses the correct SMTP class.  I'm going to remove the old class and update it using a modern one.  Should have a release out shortly.

**Comment by paintballrefjosh** [comment]
This should be fixed now in the bug-fixes branch. Pull down the files here: https://github.com/paintballrefjosh/MaNGOSWebV4/tree/bug-fixes.  If you are using Gmail you'll need to "enable less secure apps" per https://support.google.com/accounts/answer/6010255?hl=en.  I will be working on the Gmail XOAUTH2 as part of normal development and not a bug fix so it will come in the next release.

**Comment by Cubansephiroth** [comment]
Mails are sended though Admin Panel with new phpmailer class and a gmail account with less secure apps enabled. FINEEE. Also they are sended as intended with my mail server. if anyone have troubles sending mails phpmailer have an awesome debug info just change $mail->SMTPDebug = 0; to $mail->SMTPDebug = 2; in your core/common.php and you will have a detailed mail log. Thanks @paintballrefjosh  for your awesome work integrating a modern mailing class.
