### ISSUE TITLE
Cant Logout !!!

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#28]
if i clic Logout button from the frontpage it doesnt close my current session. Instead its redirects me to my account page, same behavior as if i clic profile button.

Currently using Mist of Pandaria v1.0 Theme.

**Comment by paintballrefjosh** [comment]
Make sure you have set the following correctly in your config file.  I've seen incorrect values cause some strange issues.

$site_href = '/';
$site_base_href = 'http://www.yourdomain.com/';

for $site_href make sure it matches the directory where you have MWE installed.

**Comment by Cubansephiroth** [comment]
Changed my install dir from a subdirectory to the root folder of my webserver.
Also changed my config file according to your previous comment.

$site_href = '/';
$site_base_href = 'http://10.20.6.20';    ---> ip address of my webserver LAN

cleared the cache through admin panel and still cant logout. Keeps redirectin me to my account page as if i clicked the profile buttom.

My theme is Pandaria v1.0

**Comment by paintballrefjosh** [comment]
I can't reproduce it on this side.  Try clearing the cookies, that will definitely work as that's how the site currently checks if you are logged in.  I will be changing that in a future release to provide better security.

**Comment by Demonith** [comment]
Same here cant logout and try everything and also clearing cookies nothing of it worked

**Comment by Cubansephiroth** [comment]
If I clear the cookies manually then my session is closed but the logout function is not doing his job xD I also disable the cache system to see if was something related with the cache with no luck. Still the Logout buttom not works for me and @Demonith looks like have my same issue :(

**Comment by paintballrefjosh** [comment]
What browser are you guys using?  Do you have a public URL I can create an account at and test it?  Do you see any errors on the page?  Do you see any errors in the webserver or PHP logs?

**Comment by Cubansephiroth** [comment]
Firefox 52 64bits.. Ill update my repo with your lastest commits and test again with differents browsers and ill check if any webserver php logs...

**Comment by Cubansephiroth** [comment]
Tested in Internet Explorer 11 (Still cant logout)

**Comment by Demonith** [comment]
Firefox like normal people :) 

I used old one long ago and find this maybe u guys can chack it out 
https://code.google.com/archive/p/mangoswebv3/issues/9

**Comment by Cubansephiroth** [comment]
Changed some method from POST to GET with no luck hope @paintballrefjosh find and fix the logout bug soon.

**Comment by paintballrefjosh** [comment]
I still cannot reproduce the issue.  However I found some code to clean up that may help.  Try pulling the new file:

core/SDL/class.account.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/core/SDL/class.account.php)

**Comment by Cubansephiroth** [comment]
tested with new file and still cant logout

**Comment by paintballrefjosh** [comment]
I can reproduce it now, seems to be directly related to FireFox browser.  I will run some tests and look for a fix.

**Comment by Cubansephiroth** [comment]
omg thanks

**Comment by paintballrefjosh** [comment]
Issue should now be fixed.  Grab the following files from the bug-fixes branch to test:

inc/account/account.login.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/account/account.login.php)
templates/blizzlike/account/account.login.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/templates/blizzlike/account/account.login.php)
templates/blizzlike/body_header.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/templates/blizzlike/body_header.php)

**Comment by Cubansephiroth** [comment]
AWESOMEEE Thanks!!! now i can logout fine. Closing......
