### ISSUE TITLE
Database config after latest commits

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#32]
after update my files with the latest updates cant access the Database Config section of the Admin Panel.

# Error..

<addr> Warning: include(inc/admin/template_files/admin.dbconfig.php): failed to open stream: No such file or directory in /var/www/html/index.php on line 223 Warning: include(): Failed opening 'inc/admin/template_files/admin.dbconfig.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/index.php on line 223 <addr>

**Comment by paintballrefjosh** [comment]
Found the issue, a fix will be released shortly.  The icon is actually no longer in use since we don't support writing config files (due to security) any more.

**Comment by paintballrefjosh** [comment]
This should be fixed now in the bug-fixes branch. Pull down the files here: https://github.com/paintballrefjosh/MaNGOSWebV4/tree/bug-fixes.  The issue was cosmetic and the DB Config icon/link has been disabled.

**Comment by Cubansephiroth** [comment]
icon/link properly disabled... closing..
