### ISSUE TITLE
Cant switch themes in frontpage after configs were moved to DB

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#33]
You could display the list of available themes but if you select one of the page refresh but nothing happens. You are stuck with WoTLK theme.

**Comment by paintballrefjosh** [comment]
I cannot reproduce this on my site.  Do you have a URL I could check out?  Do you see any errors in the webserver or PHP logs?

**Comment by Cubansephiroth** [comment]
After update with latest fixes in bug-fixes branch dd5a37826ab424b6cb22731f521b7d3a798913e8 now i am able to change themes from the front page.
