### ISSUE TITLE
Errors when try to register

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#34]
Now after 6800ccac2db7b0aef0b90bca46b555cad3301e5e

Some errors during registration process. After fill the form with data i got some errors. Even if i disable secrets questions in admin panel.

Account Registration
Notice: Undefined index: reg_secret_questions in /var/www/html/inc/account/account.register.php on line 99 Notice: Undefined variable: Config in /var/www/html/inc/account/account.register.php on line 173 Fatal error: Call to a member function get() on a non-object in /var/www/html/inc/account/account.register.php on line 173

**Comment by paintballrefjosh** [comment]
Found the issue, a fix will be released shortly.

**Comment by paintballrefjosh** [comment]
This should be fixed now in the bug-fixes branch.  Pull down the files here: https://github.com/paintballrefjosh/MaNGOSWebV4/tree/bug-fixes and let me know if this not works.

**Comment by Cubansephiroth** [comment]
This bug have been fixed in bug-fixes branch.. Thanks, now i have another registration bug ill post in another issue.
