### ISSUE TITLE
Error on final step of registration !!!

### ISSUE THREAD

**Issue by Cubansephiroth** [paintballrefjosh/MaNGOSWebV4#35]
I will detail all steps to reproduce the problem.

1 - Enable Account Registration in Admin Panel
2 - Enable Require Account Activation in Admin Panel
3 - Enable Require Invite in Admin panel
4 - Copy and Paste your registration Key to enable registration form
4 - Do the normal registration process (Fill the required data.. Username, password, mail, etc..)
5 - Receive registration mail in your inbox with your register details and a activation link)
6 - Clic on Link provided in the email to activate your account.

Then an error message is displayed.

![error2register](https://cloud.githubusercontent.com/assets/11562843/24421415/28f44adc-13c4-11e7-8cd2-6200e70b8180.jpg)

If i am right after d379fb1319aba2a0d161855af0a9b8a71aadebed mangosweb tables are stored in a separate DB so no account table in mangosweb DB

**Comment by paintballrefjosh** [comment]
This is now fixed, grab the new account.activate.php file under inc/account in the bug-fixes branch:

https://github.com/paintballrefjosh/MaNGOSWebV4/blob/03410e55a1f787649798ba4d75d53d90aa03a3ed/inc/account/account.activate.php

**Comment by Cubansephiroth** [comment]
Fixed
