### ISSUE TITLE
Realm not showing 

### ISSUE THREAD

**Issue by Demonith** [paintballrefjosh/MaNGOSWebV4#36]
IN admin Panel i setup everything to be shown and realm server and everything but nothing is showing ??? IS this a bug ?

**Comment by Cubansephiroth** [comment]
Confirmed, not data about realm in the front page, it was working fine before config were moved to DB

**Comment by paintballrefjosh** [comment]
This is now fixed, grab the following files in the bug-fixes branch:

core/common.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/core/common.php)
inc/admin/template_files/admin.realms.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/admin/template_files/admin.realms.php)
inc/frontpage/frontpage.index.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/frontpage/frontpage.index.php)
templates/blizzlike/whoisonline/whoisonline.index.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/templates/blizzlike/whoisonline/whoisonline.index.php)

**Comment by Demonith** [comment]
I will wait when full released anyways tnx for fixing it :D

**Comment by Cubansephiroth** [comment]
Fixed in bug-fixes branch
