### ISSUE TITLE
Vote items

### ISSUE THREAD

**Issue by Demonith** [paintballrefjosh/MaNGOSWebV4#38]
I try to add gold for vote item shop i get this 

Couldnt Run Query: INSERT INTO mw_shop_items( `item_number`, `itemset`, `gold`, `quanity`, `desc`, `wp_cost`, `realms`) VALUES( '0', '0', '500000', '', 'Gold is all u need !', '100', '0' )
Error: Incorrect integer value: '' for column 'quanity' at row 1

**Comment by paintballrefjosh** [comment]
This is now fixed, grab the following file in the bug-fixes branch:

inc/admin/script_files/admin.shop.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/admin/script_files/admin.shop.php)
