### ISSUE TITLE
News error again ??

### ISSUE THREAD

**Issue by Demonith** [paintballrefjosh/MaNGOSWebV4#42]
I try add news it was working till today here is the error 

','1','1490958537')
Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 's are on hire !!!!!

','1','1490958537')' at line 1

**Comment by paintballrefjosh** [comment]
This should be fixed in the bug-fixes branch now.  Only one file needs to be updated:

https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/admin/script_files/admin.news.php

**Comment by Demonith** [comment]
Well its working now tnx

**Comment by Cubansephiroth** [comment]
Confirmed, its working...
