### ISSUE TITLE
Vote shop not working

### ISSUE THREAD

**Issue by Demonith** [paintballrefjosh/MaNGOSWebV4#43]
I add gold but when i click add to get from points i get this

Please contact an administrator as there is an error connecting or authenticating with the server. You will NOT be charged Web Points at this time

**Comment by paintballrefjosh** [comment]
Confirmed this isn't working.  I also found a bug related to the Remote Access part of the Realm settings.  The RA is required for shop items/gold/etc. so I should have a few fixes out for this soon.

**Comment by Demonith** [comment]
Oh man do fast i need this :( 👍

**Comment by paintballrefjosh** [comment]
This should now be working.  There were also many other fixes implemented in the bug-fixes tree today.  For this issue specifically grab these files:

inc/admin/script_files/admin.realms.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/inc/admin/script_files/admin.realms.php)
core/SDL/class.rasocket.php - [here](https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/core/SDL/class.rasocket.php)

https://github.com/paintballrefjosh/MaNGOSWebV4/tree/bug-fixes
