### ISSUE TITLE
Blank Page After TOS

### ISSUE THREAD

**Issue by sixshooterz** [paintballrefjosh/MaNGOSWebV4#45]
I'm getting a blank page after accepting the Terms.  I checked the apache2 error.log file and there's nothing in there.  The access.log file only shows loading the favicon.

Any ideas?

**Comment by paintballrefjosh** [comment]
Did you run through the install script already?  Or did this happen the first time you hit the site?

**Comment by sixshooterz** [comment]
I went thru the steps. At first, with PHP7, I couldn't get past step 3. After downgrading to PHP5.6 I was able to complete all steps. After I deleted install and update folders I was able to get to the Terms of Service page. Once accepted, I get a blank page. 

I've tried restarting apache as well as the whole server. I've verified the config. I've checked the logs and am unable to find any errors.

**Comment by sixshooterz** [comment]
Closing. Apparently an issue with my apache installation. Spun up a new lamp instance and its working fine.
