### ISSUE TITLE
forms should be escaped

### ISSUE THREAD

**Issue by Albirew** [paintballrefjosh/MaNGOSWebV4#49]
putting a single-quote when editing frontage link titles bring an SQL error.
These form fields should be protecter with either addslashes() or mysqli_real_escape_string() to avoid errors and also for security reasons.

**Comment by Hellangel1987** [comment]
Hi Albirew,

did you managed to get the shop working ?

Everytime i try to buy an item in the shop i get following error:

Sending Items, Please wait...

Fatal error: Maximum execution time of 30 seconds exceeded in /srv/www/htdocs/azer/core/SDL/class.rasocket.php on line 72

i can connect to my server via telnet and username and password are matching.

**Comment by Albirew** [comment]
Yeah but with SOAP instead of RA. Using core/logs/ files, I found that I needed to open SOAP port (7878) in iptables AND in router's configuration. Your timeout is probably for the same reason so you just need to open your RA port on both server and router box...

**Comment by Hellangel1987** [comment]
Can you please tell us how do you get the SAOP working ? evertime i use SOAP i get following error

Fatal error: Class 'SoapClient' not found in /srv/www/htdocs/azer/core/SDL/class.rasocket.php on line 357

Would be great if i can get your class.rasocket.php .....

Thank you !

**Comment by Albirew** [comment]
My class.rasocket.php is the same as https://github.com/paintballrefjosh/MaNGOSWebV4/blob/master/core/SDL/class.rasocket.php
settings in manage reals -> realmname are
type: SOAP
Remote Access Port: 7878
Please also note that you must enable SOAP in your server configuration.
On TrinityCore, this is in worldserver.conf with
```php
SOAP.Enabled = 1
SOAP.IP = "0.0.0.0" #must be 0.0.0.0 and not local IP, else, you won't be able to use it
SOAP.Port = 7878
```

**Comment by Hellangel1987** [comment]
What is your ra_info table content ?

i will double check my content with yours 

ra_info      /TABLE IN realmlist DB
0;7878;ACCOUNT;PASSWORT

**Comment by Albirew** [comment]
1;7878;ACCOUNT;PASSWD

**Comment by paintballrefjosh** [comment]
Issue has been resolved and pulled into master.
