### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function simplexml_load_file()

### ISSUE THREAD

**Issue by Syn1r** [paintballrefjosh/MaNGOSWebV4#50]
Network consists of Web server and Game server.
Have allowed Web server MaNGOSWebV4 to talk to actual vanilla wow DB.
Install succeed - asked me to delete /install directory and /update directory.
Upon doing this was presented with the accept TOC page, clicked accept.
Now I get the following error everytime I browse to the page:
Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/core/class.template.php:148 Stack trace: #0 /var/www/html/index.php(164): MangosTemplate->loadTemplateXML() #1 {main} thrown in /var/www/html/core/class.template.php on line 148

**Comment by paintballrefjosh** [comment]
What version of PHP are you running?

**Comment by Estaira** [comment]
7.0 I have the same issue. I also tried 5.6 same issue.

**Comment by paintballrefjosh** [comment]
Do you have the php-xml package installed?

**Comment by Tyrelis** [comment]
Yes.

**Comment by paintballrefjosh** [comment]
Going to close this one out as I believe you are missing the php-xml package on your webserver.
