### ISSUE TITLE
Telnet not working

### ISSUE THREAD

**Issue by Hellangel1987** [paintballrefjosh/MaNGOSWebV4#51]
Everytime i try to buy an item in the shop i get following error:

Sending Items, Please wait...

Fatal error: Maximum execution time of 30 seconds exceeded in /srv/www/htdocs/azer/core/SDL/class.rasocket.php on line 72

i can connect to my server via telnet and username and password are matching. 

Can somebody point me to the right solution?

**Comment by Hellangel1987** [comment]
Looks like the error is caused by this Code:

 public function auth($user, $pass)
    {
		global $mwe_config;
		
        $user = strtoupper($user);
        fwrite($this->handle, $user."\n");
        usleep(100);
        fwrite($this->handle, $pass."\n");
        usleep(300);
		
		$return = trim(fgets($this->handle));

**Comment by paintballrefjosh** [comment]
Are you sure the settings are correct for Telnet in the MWE realm settings page?  This should be working as expected.

**Comment by Hellangel1987** [comment]
Never get that working - i now use SOAP.

**Comment by zzjty001** [comment]
When soap is turned on, it's OK to buy a single item, but if you buy a package, you will report an error: some items are not sent successfully, please contact the administrator. Switch to RA, the store will be paralyzed, nothing to buy.
