### ISSUE TITLE
SOAP not working anymore

### ISSUE THREAD

**Issue by Hellangel1987** [paintballrefjosh/MaNGOSWebV4#54]
Some people have similar problem with your soap implementation:

Notice: Undefined variable: cmd in /var/www/html/web/core/SDL/class.rasocket.php on line 310 Warning: fopen(core/logs/RA_Debug.log): failed to open stream: No such file or directory in /var/www/html/web/core/SDL/class.rasocket.php on line 195 Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 198 Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 198 Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 198 Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 198 Warning: fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 198 Warning: fclose() expects parameter 1 to be resource, boolean given in /var/www/html/web/core/SDL/class.rasocket.php on line 200

any fix available ?

**Comment by paintballrefjosh** [comment]
Make sure your web user has write privileges to /var/www/html/web/core/logs/

**Comment by paintballrefjosh** [comment]
This logging is a bad way to do it so I'll probably change it to a simple on screen error or database log instead in a future release.

**Comment by Hellangel1987** [comment]
now i set my write privileges to my web user.

it will keep me following error:

![unbenannt](https://user-images.githubusercontent.com/20953591/30867229-b37b1d06-a2db-11e7-85ab-fe707a0d131b.JPG)

**Comment by Hellangel1987** [comment]
working now was a port problem. can be resolved all working as expected
