### ISSUE TITLE
RSS Feed 

### ISSUE THREAD

**Issue by Hellangel1987** [paintballrefjosh/MaNGOSWebV4#56]
If i try to open the RSS Link i get

Cannot open file (core/cache/rss/news.xml)

any options on that ?

**Comment by paintballrefjosh** [comment]
Looks like the webserver needs write access to that folder which probably doesn't exist.

Make the folder 
`mkdir /var/www/your_html_directory/core/cache/rss`

Then change permissions
`chown apache:apache /var/www/your_html_directory/core/cache/rss`

Then try again.  If you're on windows just do some searching around to figure out the permissions.

If you get it working it should look like this: http://www.mistvale.com/rss.php

**Comment by Hellangel1987** [comment]
Works ! Thanks for your support!
