### ISSUE TITLE
Character Customize Error

### ISSUE THREAD

**Issue by Hellangel1987** [paintballrefjosh/MaNGOSWebV4#60]
If i try to customize the character i get this error:

web/web/?p=account&sub=customize

Notice: Undefined index: char_recustomize_success in /var/www/html/web/inc/account/account.customize.php on line 63

![screen](https://user-images.githubusercontent.com/20953591/31553046-742d6d64-b039-11e7-9f70-150e7737739c.JPG)

**Comment by paintballrefjosh** [comment]
The recustomize should be working properly but it seems you are missing a language variable:

`$lang['char_recustomize_success']`

In the English language it should read:

`'char_recustomize_success' => 'Re-Customize flag set! Please login with your character in-game to re-customize your character.'`
