### ISSUE TITLE
Another Broken Link

### ISSUE THREAD

**Issue by Estaira** [paintballrefjosh/MaNGOSWebV4#64]
**Modules:** ToS
**Error:** 404
**Screenshot:** http://prntscr.com/hd6fdk

I have tried to fix the 404 error related to the images. I still haven't found a solution.

**Comment by paintballrefjosh** [comment]
These should be present, references are located in file: 
`modules/notice/notice.css`

```
#posttable21 { background: url('modules/notice/images/post-til.gif') repeat-x bottom; }
...
.postdisplay div.postingcontainer21 { background: #313131 url('modules/notice/images/post-tim.gif') repeat-x top; }
```

**Comment by Estaira** [comment]
Accept the images aren't working as intended though I get a 404 error. I had to remove the images and css code from my website for the time being.

**Comment by paintballrefjosh** [comment]
Try this new CSS file in the bug-fixes branch, should fix the 404 errors:

`https://github.com/paintballrefjosh/MaNGOSWebV4/blob/bug-fixes/modules/notice/notice.css`

**Comment by Estaira** [comment]
@paintballrefjosh 
It works perfectly and fixes the 404 errors.
