### ISSUE TITLE
Error on top

### ISSUE THREAD

**Issue by Malachiel87** [paintballrefjosh/MaNGOSWebV4#69]
I keep to see this error on top:
Notice: Undefined offset: 3 in /var/www/core/class.template.php on line 126 /

**Comment by Estaira** [comment]
It looks like it's something to do with the template you have or selected.

**Comment by paintballrefjosh** [comment]
@Tyrelis Agree.  @xion87 try to select a different template/theme from the dropdown to see if it goes away.

**Comment by Malachiel87** [comment]
yeah using cataclysm one is gone

**Comment by Estaira** [comment]
That what I did to fix my issue selected different template.

**Comment by Malachiel87** [comment]
i keep to get the error and is pretty spam

> 2017/12/04 23:11:31 [error] 1991#1991: *11695 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 4 in /var/www/wow.trollandia.it/core/class.template.php on line 126" while reading response header from upstream, client: 141.101.98.163, server: wow.trollandia.it, request: "GET /?p=vote HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "wow.trollandia.it"

also

> 2017/12/05 00:56:17 [error] 16566#16566: *14141 FastCGI sent in stderr: "PHP message: PHP Notice:  Undefined offset: 4 in /var/www/wow.trollandia.it/core/class.template.php on line 126" while reading response header from upstream, client: 141.101.98.163, server: wow.trollandia.it, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "wow.trollandia.it"
