### ISSUE TITLE
Shop dont send item ingame Warning Mysqli_query expects parameter 1

### ISSUE THREAD

**Issue by cliffsmits007** [paintballrefjosh/MaNGOSWebV4#81]
Hello i got a issue when i try to buy something from the Shop.

![image](https://user-images.githubusercontent.com/8860271/39383769-c8c0e042-4a6a-11e8-8201-02217682127f.png)
![image](https://user-images.githubusercontent.com/8860271/39383791-e52511d6-4a6a-11e8-9437-e4b7f9c1a28a.png)

**Comment by ryanschulze** [comment]
`Error: MySQL server has gone away` generally means that the connection to your MySQL server isn't working, the rest seem to be subsequent problems resulting from the borked connection.
Is this the only place you see MySQL connection errors?

**Comment by cliffsmits007** [comment]
Thanks for the respond. 

Yes it happend only at the shop the rest off the site works corectly

**Comment by cliffsmits007** [comment]
Also got the site now on a domain for testing. I just noticed that the error pop up aswell at the realm status section. 

But if you go to more at a realm it self you can ser all the information it only happen by those 2 sections. So at the shop and realmstatus.  Test site www.cursewowgaming.com

**Comment by cliffsmits007** [comment]
Correction http://cursedwowgaming.com
