### ISSUE TITLE
Removing  flash module from the first page

### ISSUE THREAD

**Issue by theheartofraven** [paintballrefjosh/MaNGOSWebV4#86]
Hi! 
Sorry for this noob question, but I would like to remove the flash module from the first page, but I can't find where I can do that.

**Comment by yimgame** [comment]
U have chance to do that in admin panel there is scroll down option about and let u choice a few tings.

**Comment by yimgame** [comment]
> Hi!
> Sorry for this noob question, but I would like to remove the flash module from the first page, but I can't find where I can do that.

U have chance to do that in admin panel there is scroll down option about and let u choice a few tings.

**Comment by theheartofraven** [comment]
Thank you very much!
